- name: Get repository key
  apt_key: keyserver=hkp://keyserver.ubuntu.com:80 id=EA312927 

- name: Add new repository
  shell: echo "deb http://repo.mongodb.org/apt/debian wheezy/mongodb-org/3.2 main" | sudo tee /etc/apt/sources.list.d/mongodb-org-3.2.list

- name: Update package lists
  apt: update_cache=yes

- name: Install MongoDB
  apt: name=mongodb-org

