- name: Install and Configure VIM
  hosts: 127.0.0.1
  become: True
  vars:
    - repo: https://github.com/Ankk4/vim.git  
    - user: antero
  tasks:
      - name: Install VIM
        apt: name=vim update_cache=yes

      - name: Download My git configuration
        git: repo={{repo}} dest=/home/{{user}}/vim

      - name: Check if clone was succesful
        stat: path=/home/{{ user }}/vim 
        register: vim_stat

      - name: Move files to correct places
        command: mv /home/{{user}}/vim/.vimrc /home/{{user}}/.vimrc
        when: vim_stat.stat.exists      

      - name: Move more files
        command: mv /home/{{user}}/vim/.vim /home/{{user}}/.vim
        when: vim_stat.stat.exists
