- name: Add rabbitmq users, tags and permissions
  rabbitmq_user: user={{item.value.name}}
                 password={{item.value.password}}
                 tags={{item.value.tags}}
                 vhost={{item.value.vhost}}
                 configure_priv={{item.value.configure_priv}}
                 read_priv={{item.value.read_priv}}
                 write_priv={{item.value.write_priv}}
                 state=present
  with_dict: "{{mqtt_users}}"
  notify: rabbit_restart

- name: Install graphic control panel
  rabbitmq_plugin: names=rabbitmq_management state=enabled new_only=yes
  notify: rabbit_restart

- name: Install RabbitMQ plugins
  rabbitmq_plugin: names="{{item}}" state=enabled new_only=yes
  with_items: "{{ plugins }}"
  notify: rabbit_restart

- name: Copy config template rabbit
  template: 
    src: "rabbitmq.config.j2"
    dest: "/etc/rabbitmq/rabbitmq.config"
  notify: rabbit_restart
