- name: Configure hosts to use ansible
  hosts: all
  become: True
  vars:
    password: "ehDCm0dR9rqgE"
    user: "ansible"
    me: "antero"

  tasks:
    - name: Install vmware tools
      apt: name=open-vm-tools update_cache=yes

    - name: Remove user
      user: name={{user}} state=absent remove=yes

    - name: Create group for new user
      group: name={{user}} state=present

    - name: Create new user
      user: name={{user}} password={{password}} state=present groups="sudo,{{user}}"
    
    - name: Create .ssh directory if it doesn't exist
      file: path=/home/{{user}}/.ssh state=directory mode=0755

    - name: Copy authorized_keys file to new user
      copy: src=/home/{{me}}/.ssh/authorized_keys dest=/{{user}}/.ssh/
