- name: Install Development tools
  hosts: all
  become: True
  tasks:
  - name: Install NPM
    apt: name=npm update_cache=yes state=present

  - name: Install N
    npm: name=n state=present global=yes 

  - name: Install Nodejs
    shell: n stable

  - name: Install Nodemon
    npm: name=nodemon state=present global=yes

  - name: Install PM2
    npm: name=pm2 state=present global=yes

  - name: Install git
    apt: name=git state=present

