- name: Clean dat shit up
  shell: apt-get clean

- name: Add rabbitmq repository source
  apt_repository: repo='deb http://www.rabbitmq.com/debian/ testing main' state=present

- name: Add repository public key 
  apt_key: url=https://www.rabbitmq.com/rabbitmq-signing-key-public.asc

- name: Update packages with new sources
  apt: update_cache=true upgrade=yes force=true

- name: Install rabbitmq server
  shell: apt-get install rabbitmq-server -y --force-yes
