- name: Testing vmware vsphere module
  gather_facts: false
  hosts: local
  become: True
  roles:
      - role: jdauphant.ssl-certs
  tasks:
      - vsphere_guest:
          vcenter_hostname: vcenter01.dc.lab
          username: anteroj
          password: "password"
          guest: KAT13JAntero_CreatedWithAnsible
          state: powered_on
          vm_disk:
            disk1:
            size_gb: 16
            type: thin
            datastore: SVC-Generic-122-vm_nic
          vm_nic:
            nic1:
            type: vmxnet3
            network: vm
            network_type: standard        
          vm_hardware:
            memory_mb: 1024
            num_cpus: 1
            osid: ubuntu64Guest
            scsi: paravirtual 
          esxi:
            datacenter: DCLab
            hostname: dc-node-1.dc.lab
